#name: "Murat Yildizoglu's Blog"
description: "Bits of tricks, tips and thoughts by me. See my web site at https://yildizoglu.fr"

url: "https://myildi.github.io"
image_path: "https://myildi.github.io/images/"
pygments: true

theme: jekyll-theme-dinky

#remote_theme: pages-themes/dinky@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

